/*
 * ✉️  POSTCARDS DATA — regenerated by tools/build_cards.py.
 * You can still edit it by hand. To keep a card across regenerations, put
 * it in manual_cards.js (see README).
 *
 *   from      – who it's from
 *   photo     – single photo path
 *   photos    – several photos: [ { src, caption?, focus? } ]
 *   caption   – handwritten strip under a single photo
 *   letter    – freeform back text (verbatim, line breaks kept)
 *   at30 / wish / signoff / closing / focus
 */

window.SITE = {
  "name": "Aiyana",
  "year": 2026,
  "title": "Happy 30th, Aiyana",
  "subtitle": "Postcards from the people who love you",
  "coverPhotos": [
    {
      "src": "photos/aiyana/01.jpg",
      "focus": "50% 68%"
    },
    {
      "src": "photos/aiyana/04.jpg",
      "focus": "40% 45%"
    },
    {
      "src": "photos/aiyana/07.jpg",
      "focus": "78% 42%"
    }
  ],
  "gallery": [
    "photos/aiyana/01.jpg",
    "photos/aiyana/02.jpg",
    "photos/aiyana/03.jpg",
    "photos/aiyana/04.jpg",
    "photos/aiyana/05.jpg",
    "photos/aiyana/06.jpg",
    "photos/aiyana/07.jpg"
  ]
};

window.CARDS = [
  {
    "from": "Aaron",
    "letter": "So in 2000, I started the year at BCIT in the second semester of getting my marketing diploma.  Not a lot happened there except i lived on campus and generally just pounded through the course work.  In the summer, I went to Peregrine Lodge in Haida Gwaii where I worked as a guide and generally had a lot of fun.  The fishing there was very good and we got to see a lot of whales, seals, sea lions, bears, deer and other wild life.  In Sept, i returned to Burnaby for my 3rd semester.  It wasn’t the most exciting year for me but it was the turning point in my working career from a skilled labourer to a sales & marketing professional.  It also was the point where I returned to live back in Canada full time.\n\n\nOh the second pic in the yellow pants.  Is probably from 2021 but I threw it in because it was my personal record for a salmon",
    "photos": [
      {
        "src": "photos/aaron/01.jpg"
      },
      {
        "src": "photos/aaron/02.jpg",
        "caption": "Oh the second pic in the yellow pants.  Is probably from 2021 but I threw it in because it was my personal record for a salmon"
      }
    ]
  },
  {
    "from": "Adi",
    "letter": "2025 was a wild year. I think I was still pretty bright eyed and bushy tailed around this point. But you surprised me with a trip to Singapore where I proceeded to burn my mouth something new. Either way, I had a blast and absolutely loved my time there and the fact that I got to spend it with you!\n\n\nLove you b, glad you’re old like us now",
    "photos": [
      {
        "src": "photos/adi/01.jpg"
      },
      {
        "src": "photos/adi/02.jpg"
      },
      {
        "src": "photos/adi/03.jpg"
      },
      {
        "src": "photos/adi/04.jpg"
      },
      {
        "src": "photos/adi/05.jpg"
      },
      {
        "src": "photos/adi/06.jpg"
      },
      {
        "src": "photos/adi/07.jpg"
      },
      {
        "src": "photos/adi/08.jpg"
      },
      {
        "src": "photos/adi/09.jpg"
      }
    ]
  },
  {
    "from": "Corrine",
    "letter": "2002 I was a young lab technologist that enjoyed traveling, snowboarding and hiking. Living and working (graveyard shift)in North Vancouver. I recall snowboarding at Whistler after workong a night shift, seems crazy thinking about it now. I passed out cold in my buddy's car on the drive home.\n\n\nA couple of images for you:\nSnowboarding Kamloops 2002\nscuba diving Belize 2002\nLaughing Bird Caye 2002 (Left)",
    "photos": [
      {
        "src": "photos/corrine/01.jpg",
        "caption": "Snowboarding Kamloops 2002"
      },
      {
        "src": "photos/corrine/02.jpg",
        "caption": "scuba diving Belize 2002"
      },
      {
        "src": "photos/corrine/03.jpg",
        "caption": "Laughing Bird Caye 2002 (Left)"
      }
    ]
  },
  {
    "from": "Kala & Ravi",
    "letter": "Happy milestone birthday, dear Aiyana! May this special year mark the beginning of an even brighter, more successful, and joyful chapter ahead. We feel so fortunate to have you in our family and can’t wait to celebrate and share many more wonderful years ahead with you and Vikki. Sending you both lots of love and warm blessings ..... Ravi & Kala",
    "photos": [
      {
        "src": "photos/kala-and-ravi/01.jpg"
      },
      {
        "src": "photos/kala-and-ravi/02.jpg"
      }
    ]
  },
  {
    "from": "Lauren",
    "letter": "when I was 30 I was a bat with Florence",
    "photo": "photos/lauren/01.jpg"
  },
  {
    "from": "Nick",
    "letter": "when nick was 30 he was fucking himself up... again. At least its not the nutties this time",
    "photo": "photos/nick/01.jpg"
  },
  {
    "from": "Olivia & Graeme",
    "letter": "Graeme and I spent our 30th year travelling, we got engaged. I graduate my undergrad, and expanded our little petting zoo with a second doggo 🐶\n\n\nWe wish Aiyana a year full of adventures, love and happiness. 30 was wonderful for us and we hope it is just as great for her as well! We are excited to see where her 30th year around the sun takes her! \n\n\nHappy birthday Aiyana! 🎊🎂🎉\nWith love, Olivia and Graeme (P.S. welcome to the 30 flirty and thriving club)",
    "photo": "photos/olivia-and-graeme/01.jpg",
    "focus": "36% 55%"
  },
  {
    "from": "Sapphire",
    "letter": "2021- Sapphire starting to write her book",
    "photo": "photos/sapphire/01.jpg"
  },
  {
    "from": "Shyanne",
    "letter": "30, eh? That feels like a lifetime ago.\nI turned 30 in peak COVID times. I was living in Japan and couldn’t travel out of the country, so instead, it became the year I really got to explore Japan. I travelled to four or five different cities that year, which only made me love Japan even more. I also discovered my favourite all-you-can-eat wing spot (which, thankfully, you and I did go to).\nThis was also the year I started my annual Christmas hike — a tradition that, sadly, no longer exists lol.\nAnd I was 30 when I decided to start wearing my hair naturally curly, which might just be my favourite part of the whole year.\nJust before I turned 31, I also started doing the elevator selfies — another tradition I’m pretty proud of.\nSo, overall, 30 was a pretty good year.\nThere’s a bit of a stigma around women turning 30, but I never really felt the dread that everyone talks about. I was happy with where I was, and looking back, I think 30 was actually a pretty fun age to be.\nBut the wildest part? I was 30 when I met you! Which is kind of crazy to think about.\nIt's a milestone birthday, but don’t forget: keep it shrimple 🦐",
    "photos": [
      {
        "src": "photos/shyanne/01.jpg"
      },
      {
        "src": "photos/shyanne/02.jpg"
      },
      {
        "src": "photos/shyanne/03.jpg"
      },
      {
        "src": "photos/shyanne/04.jpg"
      },
      {
        "src": "photos/shyanne/05.jpg"
      },
      {
        "src": "photos/shyanne/06.jpg"
      },
      {
        "src": "photos/shyanne/07.jpg"
      },
      {
        "src": "photos/shyanne/08.jpg"
      }
    ]
  },
  {
    "from": "Su Hun",
    "letter": "2020 - Height of COVID/transitioning to Korea",
    "photo": "photos/su-hun/01.jpg"
  }
];
