#!/usr/bin/env python3
"""Turn a folder of postcard submissions into photos/ + cards.js.

Expected layout
---------------
MainFolder/
  Person Name/
    photo.png          + blurb.txt              (single photo)
  Other Name/
    photo1.png, photo2.jpg, ...
    main-blurb.txt
    caption1.txt, caption2.txt, ...             (optional; pairs with photoN)

Image extensions: png, jpg, jpeg, heic, webp (any case).
The person's folder name becomes the card `from` field.
Blurbs are copied verbatim into `letter`.

Manual cards (Olivia & Graeme, etc.) live in manual_cards.js and are merged
in unless a submission folder with the same name is present.

Usage
-----
  python3 tools/build_cards.py /path/to/MainFolder
  python3 tools/build_cards.py /path/to/MainFolder --no-manual
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.stderr.write(
        "ERROR: Pillow is required. Install with:\n"
        "  python3 -m pip install Pillow\n"
        "  python3 -m pip install pillow-heif   # optional, for HEIC\n"
    )
    sys.exit(1)

HEIF_OK = False
try:
    from pillow_heif import register_heif_opener

    register_heif_opener()
    HEIF_OK = True
except ImportError:
    HEIF_OK = False

IMAGE_EXT = {".png", ".jpg", ".jpeg", ".heic", ".heif", ".webp", ".jfif"}
HEIF_EXT = {".heic", ".heif"}
MAX_PX = 1200
JPEG_QUALITY = 86
SITE_DEFAULT = {
    "name": "Aiyana",
    "year": 2026,
    "title": "Happy 30th, Aiyana",
    "subtitle": "Postcards from the people who love you",
}
BLURB_NAMES = ("blurb.txt", "main-blurb.txt")
SKIP_DIR_NAMES = {".git", "__macosx", "node_modules"}

HEADER = """/*
 * ✉️  POSTCARDS DATA — this file is regenerated by tools/build_cards.py.
 * You can still edit it by hand. To keep a card across regenerations, put
 * it in manual_cards.js (see README).
 *
 *   from      – who it's from
 *   photo     – single photo path
 *   photos    – several photos: [ { src, caption?, focus? } ]
 *   caption   – handwritten strip under a single photo
 *   letter    – freeform back text (verbatim, line breaks kept)
 *   at30 / wish / signoff / closing / focus / placeholder
 */

"""


def warn(msg: str) -> None:
    print(f"WARNING: {msg}", flush=True)


def info(msg: str) -> None:
    print(msg, flush=True)


def slugify(name: str) -> str:
    s = unicodedata.normalize("NFKD", name)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "card"


def match_key(name: str) -> str:
    return slugify(name)


def is_image(path: Path) -> bool:
    if not path.is_file() or path.name.startswith(".") or path.name.startswith("._"):
        return False
    return path.suffix.lower() in IMAGE_EXT


def natural_key(name: str):
    parts = re.split(r"(\d+)", name.lower())
    return [int(p) if p.isdigit() else p for p in parts]


def photo_number(stem: str):
    m = re.search(r"(\d+)$", stem)
    return int(m.group(1)) if m else None


def find_named_file(folder: Path, names) -> Path | None:
    files = {p.name.lower(): p for p in folder.iterdir() if p.is_file()}
    for name in names:
        hit = files.get(name.lower())
        if hit:
            return hit
    return None


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def find_caption(folder: Path, number: int) -> str | None:
    hit = find_named_file(folder, (f"caption{number}.txt", f"caption_{number}.txt"))
    if not hit:
        return None
    return read_text(hit).rstrip("\n")


def extract_js_assignment(source: str, name: str):
    token = f"window.{name}"
    idx = source.find(token)
    if idx < 0:
        return None
    eq = source.find("=", idx + len(token))
    if eq < 0:
        return None
    decoder = json.JSONDecoder()
    i = eq + 1
    while i < len(source) and source[i] in " \t\r\n":
        i += 1
    try:
        value, _end = decoder.raw_decode(source, i)
    except json.JSONDecodeError:
        return None
    return value


def load_manual_cards(path: Path) -> list:
    if not path.is_file():
        warn(f"manual cards file not found: {path}")
        return []
    text = path.read_text(encoding="utf-8")
    cleaned = []
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("//"):
            continue
        cleaned.append(line)
    value = extract_js_assignment("\n".join(cleaned), "MANUAL_CARDS")
    if not isinstance(value, list):
        warn(f"could not parse window.MANUAL_CARDS from {path}")
        return []
    return [c for c in value if isinstance(c, dict) and c.get("from")]


def load_site(cards_js: Path) -> dict:
    site = dict(SITE_DEFAULT)
    if not cards_js.is_file():
        return site
    text = cards_js.read_text(encoding="utf-8")
    parsed = extract_js_assignment(text, "SITE")
    if isinstance(parsed, dict):
        site.update(parsed)
    return site


def open_image(path: Path) -> Image.Image:
    ext = path.suffix.lower()
    if ext in HEIF_EXT and not HEIF_OK:
        raise RuntimeError(
            f"cannot read {path.name} (HEIC). Install pillow-heif:\n"
            "  python3 -m pip install pillow-heif"
        )
    im = Image.open(path)
    im = ImageOps.exif_transpose(im)
    return im


def save_resized(im: Image.Image, dest: Path, max_px: int = MAX_PX) -> None:
    rgb = im.convert("RGB")
    w, h = rgb.size
    longest = max(w, h)
    if longest > max_px:
        scale = max_px / longest
        rgb = rgb.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.Resampling.LANCZOS)
    dest.parent.mkdir(parents=True, exist_ok=True)
    rgb.save(dest, "JPEG", quality=JPEG_QUALITY, optimize=True)


def collect_images(folder: Path) -> list[Path]:
    images = [p for p in folder.iterdir() if is_image(p)]
    images.sort(key=lambda p: natural_key(p.name))
    return images


def process_person(folder: Path, photos_root: Path) -> dict | None:
    name = folder.name.strip()
    images = collect_images(folder)
    blurb_path = find_named_file(folder, BLURB_NAMES)
    if not images:
        warn(f"{name!r} has no photo (png/jpg/jpeg/heic/webp)")
        return None
    if blurb_path is None:
        warn(f"{name!r} has no blurb (expected blurb.txt or main-blurb.txt)")
        letter = ""
    else:
        letter = read_text(blurb_path)
        if letter.endswith("\n"):
            letter = letter[:-1]

    slug = slugify(name)
    out_dir = photos_root / slug
    if out_dir.exists():
        for old in out_dir.glob("*"):
            if old.is_file():
                old.unlink()
    written = []
    photos = []
    for i, src in enumerate(images, start=1):
        dest = out_dir / f"{i:02d}.jpg"
        try:
            im = open_image(src)
            save_resized(im, dest)
        except Exception as exc:
            warn(f"{name!r}: skipped {src.name} ({exc})")
            continue
        number = photo_number(src.stem) or i
        caption = find_caption(folder, number)
        entry = {"src": f"photos/{slug}/{dest.name}"}
        if caption:
            entry["caption"] = caption
        photos.append(entry)
        written.append(dest.name)

    if not photos:
        warn(f"{name!r} has no usable photo after conversion")
        return None

    info(f"  {name}: {len(photos)} photo(s) → photos/{slug}/")
    card = {"from": name, "letter": letter}
    if len(photos) == 1:
        card["photo"] = photos[0]["src"]
        if photos[0].get("caption"):
            card["caption"] = photos[0]["caption"]
    else:
        card["photos"] = photos
    return card


def list_person_folders(root: Path) -> list[Path]:
    folders = []
    for child in sorted(root.iterdir(), key=lambda p: natural_key(p.name)):
        if not child.is_dir():
            continue
        if child.name.startswith(".") or child.name.lower() in SKIP_DIR_NAMES:
            continue
        folders.append(child)
    return folders


def merge_cards(imported: list, manual: list) -> list:
    imported_keys = {match_key(c["from"]) for c in imported}
    merged = list(imported)
    for card in manual:
        key = match_key(card["from"])
        if key in imported_keys:
            info(f"  replaced manual card {card['from']!r} with folder submission")
            continue
        merged.append(card)
        info(f"  kept manual card: {card['from']}")
    return merged


def sort_cards(cards: list) -> list:
    return sorted(cards, key=lambda c: (c.get("from") or "").casefold())


def js_value(value, indent: int) -> str:
    pad = "  " * indent
    inner = "  " * (indent + 1)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        if all(isinstance(x, dict) for x in value):
            parts = [inner + js_value(x, indent + 1) for x in value]
            return "[\n" + ",\n".join(parts) + "\n" + pad + "]"
        return "[" + ", ".join(js_value(x, indent) for x in value) + "]"
    if isinstance(value, dict):
        keys = list(value.keys())
        lines = []
        for key in keys:
            lines.append(f"{inner}{json.dumps(key)}: {js_value(value[key], indent + 1)}")
        return "{\n" + ",\n".join(lines) + "\n" + pad + "}"
    return json.dumps(value, ensure_ascii=False)


def write_cards_js(path: Path, site: dict, cards: list) -> None:
    site_js = js_value(site, 0)
    cards_js = js_value(cards, 0)
    path.write_text(
        HEADER + f"window.SITE = {site_js};\n\nwindow.CARDS = {cards_js};\n",
        encoding="utf-8",
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    here = Path(__file__).resolve().parent
    default_repo = here.parent
    p = argparse.ArgumentParser(
        description="Import postcard submissions into photos/ and cards.js."
    )
    p.add_argument("folder", type=Path, help="MainFolder of <Person Name>/ submissions")
    p.add_argument(
        "--repo",
        type=Path,
        default=default_repo,
        help="Site root (default: parent of tools/)",
    )
    p.add_argument(
        "--manual",
        type=Path,
        default=None,
        help="manual_cards.js to merge (default: <repo>/manual_cards.js)",
    )
    p.add_argument(
        "--no-manual",
        action="store_true",
        help="Do not merge manual_cards.js",
    )
    p.add_argument(
        "--no-sort",
        action="store_true",
        help="Keep folder order, then append leftover manual cards",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.folder.expanduser().resolve()
    repo = args.repo.expanduser().resolve()
    if not root.is_dir():
        sys.stderr.write(f"ERROR: folder not found: {root}\n")
        return 2

    photos_root = repo / "photos"
    photos_root.mkdir(parents=True, exist_ok=True)
    cards_js = repo / "cards.js"
    manual_path = args.manual
    if manual_path is None:
        manual_path = repo / "manual_cards.js"
    else:
        manual_path = manual_path.expanduser().resolve()

    info(f"Importing from {root}")
    imported = []
    people = list_person_folders(root)
    if not people:
        warn(f"no person folders found in {root}")
    for folder in people:
        card = process_person(folder, photos_root)
        if card:
            imported.append(card)

    manual = [] if args.no_manual else load_manual_cards(manual_path)
    cards = merge_cards(imported, manual)
    if not args.no_sort:
        cards = sort_cards(cards)

    site = load_site(cards_js)
    write_cards_js(cards_js, site, cards)
    info(f"Wrote {cards_js} ({len(cards)} card(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
