#!/usr/bin/env python3
"""Turn a folder of postcard submissions into photos/ + cards.js.

Expected layout
---------------
MainFolder/
  Person Name/
    photo.png          + blurb.txt | Main.txt     (single photo)
  Other Name/
    photo1.png, photo2.jpg, ...
    main-blurb.txt | Main.txt
    caption1.txt, caption2.txt, ...               (optional; pairs with photoN)
  _aiyana/                                        (optional loose photos)

Image extensions: png, jpg, jpeg, heic, webp (any case).
The person's folder name becomes the card `from` field (title-cased), unless
tools/import_hints.json overrides the display name.
Letters are copied verbatim into `letter`.

Folders that start with _ are not cards. `_aiyana/` is copied to photos/aiyana/
for the cover fan and the end-screen gallery.

Manual cards live in manual_cards.js and are merged in unless a submission
folder (or its display name) matches.

Usage
-----
  python3 tools/build_cards.py /path/to/MainFolder
  python3 tools/build_cards.py /path/to/MainFolder --no-manual
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import unicodedata
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.stderr.write(
        "ERROR: Pillow is required. Install with:\n"
        "  python3 -m pip install Pillow\n"
        "  python3 -m pip install pillow-heif   # optional, for HEIC\n"
    )
    sys.exit(1)

HEIF_OK = False
try:
    from pillow_heif import register_heif_opener

    register_heif_opener()
    HEIF_OK = True
except ImportError:
    HEIF_OK = False

IMAGE_EXT = {".png", ".jpg", ".jpeg", ".heic", ".heif", ".webp", ".jfif"}
HEIF_EXT = {".heic", ".heif"}
JPEG_EXT = {".jpg", ".jpeg"}
MAX_PX = 1600
JPEG_QUALITY = 82
SITE_DEFAULT = {
    "name": "Aiyana",
    "year": 2026,
    "title": "Happy 30th, Aiyana",
    "subtitle": "Postcards from the people who love you",
}
BLURB_NAMES = ("main.txt", "blurb.txt", "main-blurb.txt")
SKIP_DIR_NAMES = {".git", "__macosx", "node_modules"}
DT_ORIGINAL = 36867
DT_DIGITIZED = 36868
DT = 306

HEADER = """/*
 * ✉️  POSTCARDS DATA — regenerated by tools/build_cards.py.
 * You can still edit it by hand. To keep a card across regenerations, put
 * it in manual_cards.js (see README).
 *
 *   from      – who it's from
 *   photo     – single photo path
 *   photos    – several photos: [ { src, caption?, focus? } ]
 *   caption   – handwritten strip under a single photo
 *   letter    – freeform back text (verbatim, line breaks kept)
 *   at30 / wish / signoff / closing / focus
 */

"""


def warn(msg: str) -> None:
    print(f"WARNING: {msg}", flush=True)


def info(msg: str) -> None:
    print(msg, flush=True)


def slugify(name: str) -> str:
    s = unicodedata.normalize("NFKD", name)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.lower().replace("&", " and ")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "card"


def match_key(name: str) -> str:
    return slugify(name)


def is_image(path: Path) -> bool:
    if not path.is_file() or path.name.startswith(".") or path.name.startswith("._"):
        return False
    return path.suffix.lower() in IMAGE_EXT


def natural_key(name: str):
    parts = re.split(r"(\d+)", name.lower())
    return [int(p) if p.isdigit() else p for p in parts]


def photo_number(stem: str):
    m = re.search(r"(\d+)$", stem)
    return int(m.group(1)) if m else None


def find_named_file(folder: Path, names) -> Path | None:
    files = {p.name.lower(): p for p in folder.iterdir() if p.is_file()}
    for name in names:
        hit = files.get(name.lower())
        if hit:
            return hit
    return None


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def find_caption_file(folder: Path, number: int) -> str | None:
    hit = find_named_file(folder, (f"caption{number}.txt", f"caption_{number}.txt"))
    if not hit:
        return None
    return read_text(hit).rstrip("\n")


def load_hints(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        warn(f"could not parse {path}: {exc}")
        return {}


def extract_js_assignment(source: str, name: str):
    token = f"window.{name}"
    idx = source.find(token)
    if idx < 0:
        return None
    eq = source.find("=", idx + len(token))
    if eq < 0:
        return None
    decoder = json.JSONDecoder()
    i = eq + 1
    while i < len(source) and source[i] in " \t\r\n":
        i += 1
    try:
        value, _end = decoder.raw_decode(source, i)
    except json.JSONDecodeError:
        return None
    return value


def load_manual_cards(path: Path) -> list:
    if not path.is_file():
        warn(f"manual cards file not found: {path}")
        return []
    text = path.read_text(encoding="utf-8")
    cleaned = []
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("//"):
            continue
        cleaned.append(line)
    value = extract_js_assignment("\n".join(cleaned), "MANUAL_CARDS")
    if not isinstance(value, list):
        warn(f"could not parse window.MANUAL_CARDS from {path}")
        return []
    return [c for c in value if isinstance(c, dict) and c.get("from")]


def load_site(cards_js: Path) -> dict:
    site = dict(SITE_DEFAULT)
    if not cards_js.is_file():
        return site
    text = cards_js.read_text(encoding="utf-8")
    parsed = extract_js_assignment(text, "SITE")
    if isinstance(parsed, dict):
        for key, val in parsed.items():
            if key in ("coverPhotos", "gallery"):
                continue
            site[key] = val
    return site


def pretty_display_name(folder_name: str, hints: dict) -> str:
    overrides = hints.get("displayNames") or {}
    if folder_name in overrides:
        return overrides[folder_name]
    folded = {k.casefold(): v for k, v in overrides.items()}
    if folder_name.casefold() in folded:
        return folded[folder_name.casefold()]
    bits = re.split(r"(\s+|&)", folder_name.strip())
    out = []
    for bit in bits:
        if not bit or bit.isspace() or bit == "&":
            out.append(bit)
            continue
        out.append(bit[:1].upper() + bit[1:])
    return "".join(out) or folder_name


def caption_for(folder_name: str, src: Path, index: int, hints: dict) -> str | None:
    captions = hints.get("captions") or {}
    for key in (
        f"{folder_name}/{src.name}",
        f"{folder_name}/{src.stem}",
        src.name,
    ):
        if key in captions:
            return captions[key]
    file_cap = find_caption_file(src.parent, photo_number(src.stem) or index)
    return file_cap


def image_datetime(path: Path) -> str | None:
    try:
        with Image.open(path) as im:
            exif = im.getexif()
            raw = exif.get(DT_ORIGINAL) or exif.get(DT_DIGITIZED) or exif.get(DT)
            if not raw:
                try:
                    from PIL.ExifTags import IFD

                    ifd = exif.get_ifd(IFD.Exif)
                    raw = ifd.get(DT_ORIGINAL) or ifd.get(DT_DIGITIZED)
                except Exception:
                    raw = None
            if raw:
                return str(raw)
    except Exception:
        return None
    return None


def image_sort_key(path: Path):
    date = image_datetime(path)
    if date:
        return (0, date, natural_key(path.name))
    return (1, "", natural_key(path.name))


def collect_images(folder: Path, hints: dict | None = None) -> list[Path]:
    images = [p for p in folder.iterdir() if is_image(p)]
    order = ((hints or {}).get("photoOrder") or {}).get(folder.name)
    if order:
        rank = {name: i for i, name in enumerate(order)}
        images.sort(key=lambda p: (rank.get(p.name, len(rank)), natural_key(p.name)))
        return images
    images.sort(key=image_sort_key)
    return images


def open_image(path: Path) -> Image.Image:
    ext = path.suffix.lower()
    if ext in HEIF_EXT and not HEIF_OK:
        raise RuntimeError(
            f"cannot read {path.name} (HEIC). Install pillow-heif:\n"
            "  python3 -m pip install pillow-heif"
        )
    im = Image.open(path)
    im = ImageOps.exif_transpose(im)
    return im


def save_resized(im: Image.Image, dest: Path, max_px: int = MAX_PX) -> None:
    rgb = im.convert("RGB")
    w, h = rgb.size
    longest = max(w, h)
    if longest > max_px:
        scale = max_px / longest
        rgb = rgb.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.Resampling.LANCZOS)
    dest.parent.mkdir(parents=True, exist_ok=True)
    rgb.save(dest, "JPEG", quality=JPEG_QUALITY, optimize=True)


def write_photo(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if src.suffix.lower() in JPEG_EXT:
        shutil.copy2(src, dest)
        return
    im = open_image(src)
    save_resized(im, dest)


def clear_dir(path: Path) -> None:
    if not path.exists():
        return
    for old in path.iterdir():
        if old.is_file():
            old.unlink()


def process_person(folder: Path, photos_root: Path, hints: dict) -> dict | None:
    folder_name = folder.name.strip()
    images = collect_images(folder, hints)
    blurb_path = find_named_file(folder, BLURB_NAMES)
    if not images:
        warn(f"{folder_name!r} has no photo (png/jpg/jpeg/heic/webp)")
        return None
    if blurb_path is None:
        warn(f"{folder_name!r} has no letter (expected Main.txt, blurb.txt, or main-blurb.txt)")
        letter = ""
    else:
        letter = read_text(blurb_path)
        if letter.endswith("\n"):
            letter = letter[:-1]

    display = pretty_display_name(folder_name, hints)
    slug = slugify(display)
    out_dir = photos_root / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    clear_dir(out_dir)

    photos = []
    for i, src in enumerate(images, start=1):
        dest = out_dir / f"{i:02d}.jpg"
        try:
            write_photo(src, dest)
        except Exception as exc:
            warn(f"{folder_name!r}: skipped {src.name} ({exc})")
            continue
        entry = {"src": f"photos/{slug}/{dest.name}"}
        cap = caption_for(folder_name, src, i, hints)
        if cap:
            entry["caption"] = cap
        photos.append(entry)

    if not photos:
        warn(f"{folder_name!r} has no usable photo after conversion")
        return None

    info(f"  {display}: {len(photos)} photo(s) → photos/{slug}/")
    card = {"from": display, "letter": letter}
    focus_map = hints.get("focus") or {}
    focus = focus_map.get(folder_name) or focus_map.get(display)
    if len(photos) == 1:
        card["photo"] = photos[0]["src"]
        if photos[0].get("caption"):
            card["caption"] = photos[0]["caption"]
        if focus:
            card["focus"] = focus
    else:
        if focus:
            for p in photos:
                p.setdefault("focus", focus)
        card["photos"] = photos
    return card


def process_loose_album(folder: Path, photos_root: Path, hints: dict, slug: str = "aiyana") -> list[dict]:
    images = collect_images(folder, hints)
    if not images:
        warn(f"{folder.name!r} has no photos")
        return []
    out_dir = photos_root / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    clear_dir(out_dir)
    written = []
    name_to_src = {}
    for i, src in enumerate(images, start=1):
        dest = out_dir / f"{i:02d}.jpg"
        try:
            write_photo(src, dest)
        except Exception as exc:
            warn(f"{folder.name!r}: skipped {src.name} ({exc})")
            continue
        rel = f"photos/{slug}/{dest.name}"
        written.append({"src": rel, "name": src.name})
        name_to_src[src.name] = rel
    info(f"  gallery {folder.name}: {len(written)} photo(s) → photos/{slug}/")

    cover_names = hints.get("cover") or [w["name"] for w in written[:3]]
    cover_focus = hints.get("coverFocus") or {}
    cover = []
    for name in cover_names:
        if name not in name_to_src:
            warn(f"cover photo {name!r} not found in {folder.name}")
            continue
        item = {"src": name_to_src[name]}
        if name in cover_focus:
            item["focus"] = cover_focus[name]
        cover.append(item)
    if not cover:
        cover = [{"src": w["src"]} for w in written[:3]]
    return [{"_cover": cover, "_gallery": [w["src"] for w in written]}]


def list_person_folders(root: Path) -> list[Path]:
    folders = []
    for child in sorted(root.iterdir(), key=lambda p: natural_key(p.name)):
        if not child.is_dir():
            continue
        if child.name.startswith(".") or child.name.startswith("_"):
            continue
        if child.name.lower() in SKIP_DIR_NAMES:
            continue
        folders.append(child)
    return folders


def merge_cards(imported: list, manual: list) -> list:
    imported_keys = {match_key(c["from"]) for c in imported}
    merged = list(imported)
    for card in manual:
        key = match_key(card["from"])
        if key in imported_keys:
            info(f"  replaced manual card {card['from']!r} with folder submission")
            continue
        merged.append(card)
        info(f"  kept manual card: {card['from']}")
    return merged


def sort_cards(cards: list) -> list:
    return sorted(cards, key=lambda c: (c.get("from") or "").casefold())


def js_value(value, indent: int) -> str:
    pad = "  " * indent
    inner = "  " * (indent + 1)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        if all(isinstance(x, dict) for x in value):
            parts = [inner + js_value(x, indent + 1) for x in value]
            return "[\n" + ",\n".join(parts) + "\n" + pad + "]"
        if all(isinstance(x, str) for x in value):
            parts = [inner + js_value(x, indent + 1) for x in value]
            return "[\n" + ",\n".join(parts) + "\n" + pad + "]"
        return "[" + ", ".join(js_value(x, indent) for x in value) + "]"
    if isinstance(value, dict):
        keys = list(value.keys())
        lines = []
        for key in keys:
            lines.append(f"{inner}{json.dumps(key)}: {js_value(value[key], indent + 1)}")
        return "{\n" + ",\n".join(lines) + "\n" + pad + "}"
    return json.dumps(value, ensure_ascii=False)


def write_cards_js(path: Path, site: dict, cards: list) -> None:
    site_js = js_value(site, 0)
    cards_js = js_value(cards, 0)
    path.write_text(
        HEADER + f"window.SITE = {site_js};\n\nwindow.CARDS = {cards_js};\n",
        encoding="utf-8",
    )


def prune_photos(photos_root: Path, keep_slugs: set[str]) -> None:
    if not photos_root.is_dir():
        return
    for child in photos_root.iterdir():
        if child.is_dir() and child.name not in keep_slugs:
            for f in child.rglob("*"):
                if f.is_file():
                    f.unlink()
            try:
                child.rmdir()
            except OSError:
                pass
            info(f"  removed leftover photos/{child.name}/")
        elif child.is_file() and child.suffix.lower() in IMAGE_EXT:
            child.unlink()
            info(f"  removed leftover {child.relative_to(photos_root.parent)}")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    here = Path(__file__).resolve().parent
    default_repo = here.parent
    p = argparse.ArgumentParser(
        description="Import postcard submissions into photos/ and cards.js."
    )
    p.add_argument("folder", type=Path, help="MainFolder of <Person Name>/ submissions")
    p.add_argument(
        "--repo",
        type=Path,
        default=default_repo,
        help="Site root (default: parent of tools/)",
    )
    p.add_argument(
        "--manual",
        type=Path,
        default=None,
        help="manual_cards.js to merge (default: <repo>/manual_cards.js)",
    )
    p.add_argument(
        "--hints",
        type=Path,
        default=None,
        help="import_hints.json (default: tools/import_hints.json)",
    )
    p.add_argument(
        "--no-manual",
        action="store_true",
        help="Do not merge manual_cards.js",
    )
    p.add_argument(
        "--no-sort",
        action="store_true",
        help="Keep folder order, then append leftover manual cards",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.folder.expanduser().resolve()
    repo = args.repo.expanduser().resolve()
    if not root.is_dir():
        sys.stderr.write(f"ERROR: folder not found: {root}\n")
        return 2

    photos_root = repo / "photos"
    photos_root.mkdir(parents=True, exist_ok=True)
    cards_js = repo / "cards.js"
    manual_path = args.manual
    if manual_path is None:
        manual_path = repo / "manual_cards.js"
    else:
        manual_path = manual_path.expanduser().resolve()
    hints_path = args.hints or (Path(__file__).resolve().parent / "import_hints.json")
    hints = load_hints(hints_path)

    info(f"Importing from {root}")
    imported = []
    people = list_person_folders(root)
    if not people:
        warn(f"no person folders found in {root}")
    for folder in people:
        card = process_person(folder, photos_root, hints)
        if card:
            imported.append(card)

    cover_photos = []
    gallery = []
    loose = root / "_aiyana"
    if loose.is_dir():
        extra = process_loose_album(loose, photos_root, hints)
        if extra:
            cover_photos = extra[0]["_cover"]
            gallery = extra[0]["_gallery"]

    manual = [] if args.no_manual else load_manual_cards(manual_path)
    cards = merge_cards(imported, manual)
    if not args.no_sort:
        cards = sort_cards(cards)

    site = load_site(cards_js)
    if cover_photos:
        site["coverPhotos"] = cover_photos
    if gallery:
        site["gallery"] = gallery

    keep = {slugify(c["from"]) for c in cards}
    if gallery:
        keep.add("aiyana")
    prune_photos(photos_root, keep)

    write_cards_js(cards_js, site, cards)
    info(f"Wrote {cards_js} ({len(cards)} card(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
